version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
<<<<<<< HEAD
      time: 00:00
=======
      time: '00:10'
>>>>>>> 2934d9a (Update .github/dependabot.yml)
