name: Validate OWASP metadata file

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '*.owasp.yaml'

  push:
    paths:
      - '*.owasp.yaml'

concurrency:
  cancel-in-progress: true
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}

jobs:
  validate-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate OWASP metadata file
        # We want always use the latest version of the action from `main` branch.
        # The action lives in the `owasp/nest-schema` repository subdirectory and doesn't have
        # a separate release process. This approach simplifies the workflow support however
        # you can change it to use a specific SHA version if needed.
        uses: owasp/nest-schema/.github/actions/validate@main  # NOSONAR
